version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fanjam-db
    environment:
      POSTGRES_USER: fanjam
      POSTGRES_PASSWORD: fanjam123
      POSTGRES_DB: fanjamdb
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - fanjam-network

  backend:
    build:
      context: ./backend
    container_name: fanjam-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fanjamdb
      SPRING_DATASOURCE_USERNAME: fanjam
      SPRING_DATASOURCE_PASSWORD: fanjam123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - fanjam-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fanjam-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fanjam.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fanjam-network

networks:
  fanjam-network:
    driver: bridge
